version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_conn
    environment:
      POSTGRES_DB: finproaju
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  springboot-app:
    image: tcare_img
    container_name: tcare_conn
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finproaju
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
